[package]
name = 'stream'
version = '1.0.0'

[addresses]
stream = "_"

[dev-addresses]
stream = "0xcafe"
stream_managers = "0xcafe1"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosStdlib = { local = "../framework/aptos-stdlib" }
AptosTokenObjects = { local = "../framework/aptos-token-objects" }
stream_managers = { local = "../stream-managers" }
